[2025-03-26T10:22:06.485+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-26T10:22:06.491+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: naver_dag.extract scheduled__2025-03-25T00:01:00+00:00 [queued]>
[2025-03-26T10:22:06.493+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: naver_dag.extract scheduled__2025-03-25T00:01:00+00:00 [queued]>
[2025-03-26T10:22:06.494+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-03-26T10:22:06.497+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract> on 2025-03-25 00:01:00+00:00
[2025-03-26T10:22:06.500+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=415) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-26T10:22:06.500+0000] {standard_task_runner.py:72} INFO - Started process 416 to run task
[2025-03-26T10:22:06.501+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'naver_dag', 'extract', 'scheduled__2025-03-25T00:01:00+00:00', '--job-id', '351', '--raw', '--subdir', 'DAGS_FOLDER/naver_dag.py', '--cfg-path', '/tmp/tmpo0629dpd']
[2025-03-26T10:22:06.501+0000] {standard_task_runner.py:105} INFO - Job 351: Subtask extract
[2025-03-26T10:22:06.517+0000] {task_command.py:467} INFO - Running <TaskInstance: naver_dag.extract scheduled__2025-03-25T00:01:00+00:00 [running]> on host 910062d51134
[2025-03-26T10:22:06.542+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='naver_dag' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-03-25T00:01:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-25T00:01:00+00:00'
[2025-03-26T10:22:06.543+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-26T10:22:06.543+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-26T10:22:06.543+0000] {logging_mixin.py:190} INFO - Current task name:extract state:running start_date:2025-03-26 10:22:06.491839+00:00
[2025-03-26T10:22:06.543+0000] {logging_mixin.py:190} INFO - Dag name:naver_dag and current dag run status:running
[2025-03-26T10:22:06.543+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-26T10:22:07.149+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/naver_dag.py", line 32, in extract
    return extract_naver_data()
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/scripts/extract/naver_extract.py", line 67, in extract_naver_data
    daily_news = total_news - prev_news
                 ~~~~~~~~~~~^~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'
[2025-03-26T10:22:07.153+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-26T10:22:07.153+0000] {logging_mixin.py:190} INFO - Task start:2025-03-26 10:22:06.491839+00:00 end:2025-03-26 10:22:07.153292+00:00 duration:0.661453
[2025-03-26T10:22:07.153+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract> dag:<DAG: naver_dag> dagrun:<DagRun naver_dag @ 2025-03-25 00:01:00+00:00: scheduled__2025-03-25T00:01:00+00:00, state:running, queued_at: 2025-03-26 10:16:59.732040+00:00. externally triggered: False>
[2025-03-26T10:22:07.153+0000] {logging_mixin.py:190} INFO - Failure caused by unsupported operand type(s) for -: 'int' and 'NoneType'
[2025-03-26T10:22:07.154+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=naver_dag, task_id=extract, run_id=scheduled__2025-03-25T00:01:00+00:00, execution_date=20250325T000100, start_date=20250326T102206, end_date=20250326T102207
[2025-03-26T10:22:07.161+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-26T10:22:07.162+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 351 for task extract (unsupported operand type(s) for -: 'int' and 'NoneType'; 416)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/naver_dag.py", line 32, in extract
    return extract_naver_data()
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/scripts/extract/naver_extract.py", line 67, in extract_naver_data
    daily_news = total_news - prev_news
                 ~~~~~~~~~~~^~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'
[2025-03-26T10:22:07.178+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-26T10:22:07.186+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-26T10:22:07.188+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
