[2025-03-26T15:35:05.136+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-26T15:35:05.141+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_dag.extract manual__2025-03-26T15:16:27.935507+00:00 [queued]>
[2025-03-26T15:35:05.144+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_dag.extract manual__2025-03-26T15:16:27.935507+00:00 [queued]>
[2025-03-26T15:35:05.144+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-03-26T15:35:05.148+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract> on 2025-03-26 15:16:27.935507+00:00
[2025-03-26T15:35:05.150+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=924) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-26T15:35:05.151+0000] {standard_task_runner.py:72} INFO - Started process 925 to run task
[2025-03-26T15:35:05.152+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'google_dag', 'extract', 'manual__2025-03-26T15:16:27.935507+00:00', '--job-id', '379', '--raw', '--subdir', 'DAGS_FOLDER/google_dag.py', '--cfg-path', '/tmp/tmpua84k6rn']
[2025-03-26T15:35:05.152+0000] {standard_task_runner.py:105} INFO - Job 379: Subtask extract
[2025-03-26T15:35:05.168+0000] {task_command.py:467} INFO - Running <TaskInstance: google_dag.extract manual__2025-03-26T15:16:27.935507+00:00 [running]> on host f8bccaf06f4c
[2025-03-26T15:35:05.200+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_dag' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-03-26T15:16:27.935507+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-26T15:16:27.935507+00:00'
[2025-03-26T15:35:05.200+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-26T15:35:05.201+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-26T15:35:05.201+0000] {logging_mixin.py:190} INFO - Current task name:extract state:running start_date:2025-03-26 15:35:05.142089+00:00
[2025-03-26T15:35:05.201+0000] {logging_mixin.py:190} INFO - Dag name:google_dag and current dag run status:running
[2025-03-26T15:35:05.201+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-26T15:53:09.080+0000] {job.py:229} INFO - Heartbeat recovered after 464.07 seconds
[2025-03-26T16:19:58.190+0000] {job.py:229} INFO - Heartbeat recovered after 1311.87 seconds
[2025-03-26T16:37:57.356+0000] {job.py:229} INFO - Heartbeat recovered after 907.82 seconds
[2025-03-26T16:57:07.612+0000] {job.py:229} INFO - Heartbeat recovered after 1034.38 seconds
[2025-03-26T18:11:33.673+0000] {job.py:229} INFO - Heartbeat recovered after 4440.84 seconds
[2025-03-26T18:40:53.463+0000] {job.py:229} INFO - Heartbeat recovered after 1734.61 seconds
[2025-03-26T19:41:52.867+0000] {job.py:229} INFO - Heartbeat recovered after 3634.15 seconds
[2025-03-26T20:16:17.445+0000] {job.py:229} INFO - Heartbeat recovered after 2039.40 seconds
[2025-03-26T21:17:21.217+0000] {job.py:229} INFO - Heartbeat recovered after 3638.59 seconds
[2025-03-26T21:59:48.452+0000] {job.py:229} INFO - Heartbeat recovered after 2522.10 seconds
[2025-03-26T22:30:55.089+0000] {job.py:229} INFO - Heartbeat recovered after 1841.45 seconds
[2025-03-26T23:32:40.245+0000] {job.py:229} INFO - Heartbeat recovered after 3679.87 seconds
[2025-03-27T00:46:55.400+0000] {job.py:229} INFO - Heartbeat recovered after 4430.00 seconds
[2025-03-27T00:47:03.274+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=2, connect=5, read=4, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /trends/api/widgetdata/multiline?req=%7B%22time%22%3A+%222025-03-25+2025-03-25%22%2C+%22resolution%22%3A+%22DAY%22%2C+%22locale%22%3A+%22ko%22%2C+%22comparisonItem%22%3A+%5B%7B%22geo%22%3A+%7B%22country%22%3A+%22KR%22%7D%2C+%22complexKeywordsRestriction%22%3A+%7B%22keyword%22%3A+%5B%7B%22type%22%3A+%22BROAD%22%2C+%22value%22%3A+%22%5Cuc774%5Cuc900%5Cuc11d%22%7D%5D%7D%7D%5D%2C+%22requestOptions%22%3A+%7B%22property%22%3A+%22%22%2C+%22backend%22%3A+%22IZG%22%2C+%22category%22%3A+0%7D%2C+%22userConfig%22%3A+%7B%22userType%22%3A+%22USER_TYPE_SCRAPER%22%7D%7D&token=APP6_UEAAAAAZ-XmvqwISGXIxtAFMwQgjUtJIIBV8OCq&tz=540
[2025-03-27T01:47:54.717+0000] {job.py:229} INFO - Heartbeat recovered after 3634.14 seconds
[2025-03-27T02:48:54.141+0000] {job.py:229} INFO - Heartbeat recovered after 3634.20 seconds
[2025-03-27T03:49:53.607+0000] {job.py:229} INFO - Heartbeat recovered after 3634.12 seconds
[2025-03-27T04:50:53.064+0000] {job.py:229} INFO - Heartbeat recovered after 3634.20 seconds
[2025-03-27T04:51:13.391+0000] {connectionpool.py:823} WARNING - Retrying (Retry(total=2, connect=5, read=4, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /trends/api/widgetdata/multiline?req=%7B%22time%22%3A+%222025-03-25+2025-03-25%22%2C+%22resolution%22%3A+%22DAY%22%2C+%22locale%22%3A+%22ko%22%2C+%22comparisonItem%22%3A+%5B%7B%22geo%22%3A+%7B%22country%22%3A+%22KR%22%7D%2C+%22complexKeywordsRestriction%22%3A+%7B%22keyword%22%3A+%5B%7B%22type%22%3A+%22BROAD%22%2C+%22value%22%3A+%22%5Cuc870%5Cuad6d%22%7D%5D%7D%7D%5D%2C+%22requestOptions%22%3A+%7B%22property%22%3A+%22%22%2C+%22backend%22%3A+%22IZG%22%2C+%22category%22%3A+0%7D%2C+%22userConfig%22%3A+%7B%22userType%22%3A+%22USER_TYPE_SCRAPER%22%7D%7D&token=APP6_UEAAAAAZ-YoYdBRxSihD1QmklpIhmvpEyampTCU&tz=540
[2025-03-27T05:23:30.795+0000] {job.py:229} INFO - Heartbeat recovered after 1937.56 seconds
[2025-03-27T05:36:08.331+0000] {job.py:229} INFO - Heartbeat recovered after 732.33 seconds
