[2025-03-15T22:44:14.635+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-15T22:44:14.657+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: instant_stock_dag.load manual__2025-03-15T22:42:44.591686+00:00 [queued]>
[2025-03-15T22:44:14.677+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: instant_stock_dag.load manual__2025-03-15T22:42:44.591686+00:00 [queued]>
[2025-03-15T22:44:14.678+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-15T22:44:14.698+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load> on 2025-03-15 22:42:44.591686+00:00
[2025-03-15T22:44:14.704+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=507) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-15T22:44:14.707+0000] {standard_task_runner.py:72} INFO - Started process 508 to run task
[2025-03-15T22:44:14.707+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'instant_stock_dag', 'load', 'manual__2025-03-15T22:42:44.591686+00:00', '--job-id', '201', '--raw', '--subdir', 'DAGS_FOLDER/blog_dag.py', '--cfg-path', '/tmp/tmpc9anxu2z']
[2025-03-15T22:44:14.711+0000] {standard_task_runner.py:105} INFO - Job 201: Subtask load
[2025-03-15T22:44:14.772+0000] {task_command.py:467} INFO - Running <TaskInstance: instant_stock_dag.load manual__2025-03-15T22:42:44.591686+00:00 [running]> on host 5c3402afb028
[2025-03-15T22:44:14.830+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='instant_stock_dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2025-03-15T22:42:44.591686+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-15T22:42:44.591686+00:00'
[2025-03-15T22:44:14.830+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-15T22:44:14.832+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-15T22:44:14.834+0000] {logging_mixin.py:190} INFO - Current task name:load state:running start_date:2025-03-15 22:44:14.657896+00:00
[2025-03-15T22:44:14.835+0000] {logging_mixin.py:190} INFO - Dag name:instant_stock_dag and current dag run status:running
[2025-03-15T22:44:14.836+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-15T22:44:14.868+0000] {warnings.py:112} WARNING - /opt/***/dags/blog_dag.py:64: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_json(df_json, orient="records")  # ✅ split → records로 변경

[2025-03-15T22:44:14.905+0000] {logging_mixin.py:190} INFO - ✅ Loaded 248 rows from XCom
[2025-03-15T22:44:14.922+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/blog_dag.py", line 120, in load
    load_stock_data(extracted_data_json)
  File "/opt/airflow/dags/blog_dag.py", line 75, in load_stock_data
    cur.execute("""
psycopg2.errors.ForeignKeyViolation: insert or update on table "stock_log" violates foreign key constraint "stock_log_stock_code_fkey"
DETAIL:  Key (stock_code)=(39240) is not present in table "stock_info".

[2025-03-15T22:44:14.979+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-15T22:44:14.981+0000] {logging_mixin.py:190} INFO - Task start:2025-03-15 22:44:14.657896+00:00 end:2025-03-15 22:44:14.978730+00:00 duration:0.320834
[2025-03-15T22:44:14.984+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): load> dag:<DAG: instant_stock_dag> dagrun:<DagRun instant_stock_dag @ 2025-03-15 22:42:44.591686+00:00: manual__2025-03-15T22:42:44.591686+00:00, state:running, queued_at: 2025-03-15 22:42:44.601005+00:00. externally triggered: True>
[2025-03-15T22:44:14.985+0000] {logging_mixin.py:190} INFO - Failure caused by insert or update on table "stock_log" violates foreign key constraint "stock_log_stock_code_fkey"
DETAIL:  Key (stock_code)=(39240) is not present in table "stock_info".
[2025-03-15T22:44:14.987+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=instant_stock_dag, task_id=load, run_id=manual__2025-03-15T22:42:44.591686+00:00, execution_date=20250315T224244, start_date=20250315T224414, end_date=20250315T224414
[2025-03-15T22:44:15.020+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-15T22:44:15.021+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 201 for task load (insert or update on table "stock_log" violates foreign key constraint "stock_log_stock_code_fkey"
DETAIL:  Key (stock_code)=(39240) is not present in table "stock_info".
; 508)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/blog_dag.py", line 120, in load
    load_stock_data(extracted_data_json)
  File "/opt/airflow/dags/blog_dag.py", line 75, in load_stock_data
    cur.execute("""
psycopg2.errors.ForeignKeyViolation: insert or update on table "stock_log" violates foreign key constraint "stock_log_stock_code_fkey"
DETAIL:  Key (stock_code)=(39240) is not present in table "stock_info".

[2025-03-15T22:44:15.056+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-15T22:44:15.118+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-15T22:44:15.121+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
