[2025-03-25T10:40:47.842+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-25T10:40:47.848+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: naver_dag.extract manual__2025-03-25T10:40:44.530825+00:00 [queued]>
[2025-03-25T10:40:47.850+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: naver_dag.extract manual__2025-03-25T10:40:44.530825+00:00 [queued]>
[2025-03-25T10:40:47.851+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-25T10:40:47.855+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract> on 2025-03-25 10:40:44.530825+00:00
[2025-03-25T10:40:47.858+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1314) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-25T10:40:47.858+0000] {standard_task_runner.py:72} INFO - Started process 1315 to run task
[2025-03-25T10:40:47.859+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'naver_dag', 'extract', 'manual__2025-03-25T10:40:44.530825+00:00', '--job-id', '334', '--raw', '--subdir', 'DAGS_FOLDER/naver_dag.py', '--cfg-path', '/tmp/tmpxi3q3d5c']
[2025-03-25T10:40:47.859+0000] {standard_task_runner.py:105} INFO - Job 334: Subtask extract
[2025-03-25T10:40:47.878+0000] {task_command.py:467} INFO - Running <TaskInstance: naver_dag.extract manual__2025-03-25T10:40:44.530825+00:00 [running]> on host f0bb29838910
[2025-03-25T10:40:47.905+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='naver_dag' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-03-25T10:40:44.530825+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-25T10:40:44.530825+00:00'
[2025-03-25T10:40:47.906+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-25T10:40:47.906+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-25T10:40:47.906+0000] {logging_mixin.py:190} INFO - Current task name:extract state:running start_date:2025-03-25 10:40:47.848886+00:00
[2025-03-25T10:40:47.906+0000] {logging_mixin.py:190} INFO - Dag name:naver_dag and current dag run status:running
[2025-03-25T10:40:47.906+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-25T10:40:47.910+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/naver_dag.py", line 31, in extract
    return extract_naver_data()
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/scripts/extract/naver_extract.py", line 55, in extract_naver_data
    prev_counts = get_previous_cumulative_counts()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/scripts/extract/naver_extract.py", line 40, in get_previous_cumulative_counts
    cur.execute("""
psycopg2.errors.UndefinedColumn: column "total_news_count" does not exist
LINE 2:         SELECT keyword, total_news_count, total_blog_count
                                ^

[2025-03-25T10:40:47.916+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-25T10:40:47.916+0000] {logging_mixin.py:190} INFO - Task start:2025-03-25 10:40:47.848886+00:00 end:2025-03-25 10:40:47.915821+00:00 duration:0.066935
[2025-03-25T10:40:47.916+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract> dag:<DAG: naver_dag> dagrun:<DagRun naver_dag @ 2025-03-25 10:40:44.530825+00:00: manual__2025-03-25T10:40:44.530825+00:00, state:running, queued_at: 2025-03-25 10:40:44.557114+00:00. externally triggered: True>
[2025-03-25T10:40:47.916+0000] {logging_mixin.py:190} INFO - Failure caused by column "total_news_count" does not exist
LINE 2:         SELECT keyword, total_news_count, total_blog_count
                                ^
[2025-03-25T10:40:47.916+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=naver_dag, task_id=extract, run_id=manual__2025-03-25T10:40:44.530825+00:00, execution_date=20250325T104044, start_date=20250325T104047, end_date=20250325T104047
[2025-03-25T10:40:47.926+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-25T10:40:47.926+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 334 for task extract (column "total_news_count" does not exist
LINE 2:         SELECT keyword, total_news_count, total_blog_count
                                ^
; 1315)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/naver_dag.py", line 31, in extract
    return extract_naver_data()
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/scripts/extract/naver_extract.py", line 55, in extract_naver_data
    prev_counts = get_previous_cumulative_counts()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/scripts/extract/naver_extract.py", line 40, in get_previous_cumulative_counts
    cur.execute("""
psycopg2.errors.UndefinedColumn: column "total_news_count" does not exist
LINE 2:         SELECT keyword, total_news_count, total_blog_count
                                ^

[2025-03-25T10:40:47.960+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-25T10:40:47.968+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-25T10:40:47.968+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
