[2025-03-25T05:27:03.783+0000] {processor.py:186} INFO - Started process (PID=92) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:27:03.784+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:27:03.785+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:27:03.785+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:27:03.788+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:27:03.787+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:27:03.788+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:27:03.795+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.015 seconds
[2025-03-25T05:27:34.142+0000] {processor.py:186} INFO - Started process (PID=157) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:27:34.142+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:27:34.144+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:27:34.144+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:27:34.147+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:27:34.146+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:27:34.147+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:27:34.155+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.016 seconds
[2025-03-25T05:28:04.201+0000] {processor.py:186} INFO - Started process (PID=224) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:28:04.202+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:28:04.203+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:28:04.203+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:28:04.209+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:28:04.209+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:28:04.210+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:28:04.223+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.025 seconds
[2025-03-25T05:28:34.780+0000] {processor.py:186} INFO - Started process (PID=291) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:28:34.780+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:28:34.781+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:28:34.781+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:28:34.784+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:28:34.784+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:28:34.785+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:28:34.793+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.015 seconds
[2025-03-25T05:29:05.266+0000] {processor.py:186} INFO - Started process (PID=358) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:29:05.266+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:29:05.267+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:29:05.267+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:29:05.270+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:29:05.269+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:29:05.270+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:29:05.278+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.014 seconds
[2025-03-25T05:29:35.675+0000] {processor.py:186} INFO - Started process (PID=431) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:29:35.676+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:29:35.677+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:29:35.676+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:29:35.680+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:29:35.679+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:29:35.680+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:29:35.687+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.015 seconds
[2025-03-25T05:30:06.220+0000] {processor.py:186} INFO - Started process (PID=497) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:30:06.220+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:30:06.221+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:30:06.221+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:30:06.224+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:30:06.224+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:30:06.224+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:30:06.231+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.014 seconds
[2025-03-25T05:30:36.672+0000] {processor.py:186} INFO - Started process (PID=564) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:30:36.672+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:30:36.673+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:30:36.673+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:30:36.676+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:30:36.675+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:30:36.676+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:30:36.682+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.013 seconds
[2025-03-25T05:31:06.997+0000] {processor.py:186} INFO - Started process (PID=631) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:31:06.997+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:31:06.998+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:31:06.998+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:31:07.001+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:31:07.001+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:31:07.002+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:31:07.010+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.015 seconds
[2025-03-25T05:31:37.053+0000] {processor.py:186} INFO - Started process (PID=697) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:31:37.054+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:31:37.056+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:31:37.056+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:31:37.062+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:31:37.061+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:31:37.063+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:31:37.074+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.024 seconds
[2025-03-25T05:32:07.173+0000] {processor.py:186} INFO - Started process (PID=764) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:32:07.174+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:32:07.176+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:32:07.176+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:32:07.183+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:32:07.182+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:32:07.183+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:32:07.197+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.028 seconds
[2025-03-25T05:32:37.237+0000] {processor.py:186} INFO - Started process (PID=830) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:32:37.238+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:32:37.240+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:32:37.240+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:32:37.247+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:32:37.246+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:32:37.247+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:32:37.261+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.031 seconds
[2025-03-25T05:33:07.501+0000] {processor.py:186} INFO - Started process (PID=898) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:33:07.501+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:33:07.503+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:33:07.503+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:33:07.515+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:33:07.513+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:33:07.515+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:33:07.527+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.031 seconds
[2025-03-25T05:33:37.592+0000] {processor.py:186} INFO - Started process (PID=965) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:33:37.593+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:33:37.595+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:33:37.594+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:33:37.603+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:33:37.602+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:33:37.603+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:33:37.616+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.029 seconds
[2025-03-25T05:34:08.142+0000] {processor.py:186} INFO - Started process (PID=1032) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:34:08.143+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:34:08.145+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:34:08.145+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:34:08.153+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:34:08.151+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:34:08.153+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:34:08.166+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.028 seconds
[2025-03-25T05:34:38.380+0000] {processor.py:186} INFO - Started process (PID=1099) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:34:38.381+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:34:38.383+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:34:38.383+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:34:38.391+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:34:38.390+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:34:38.392+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:34:38.404+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.028 seconds
[2025-03-25T05:35:08.565+0000] {processor.py:186} INFO - Started process (PID=1166) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:35:08.566+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:35:08.568+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:35:08.568+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:35:08.576+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:35:08.575+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:35:08.576+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:35:08.587+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.027 seconds
[2025-03-25T05:35:38.985+0000] {processor.py:186} INFO - Started process (PID=1233) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:35:38.986+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:35:38.989+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:35:38.989+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:35:38.996+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:35:38.995+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:35:38.999+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:35:39.009+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.029 seconds
[2025-03-25T05:36:09.210+0000] {processor.py:186} INFO - Started process (PID=1300) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:36:09.211+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:36:09.212+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:36:09.212+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:36:09.220+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:36:09.219+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:36:09.220+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:36:09.232+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.026 seconds
[2025-03-25T05:36:39.397+0000] {processor.py:186} INFO - Started process (PID=1366) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:36:39.398+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:36:39.399+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:36:39.399+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:36:39.408+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:36:39.407+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:36:39.409+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:36:39.424+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.032 seconds
[2025-03-25T05:37:09.654+0000] {processor.py:186} INFO - Started process (PID=1433) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:37:09.655+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:37:09.657+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:37:09.657+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:37:09.666+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:37:09.664+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:37:09.667+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:37:09.677+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.027 seconds
[2025-03-25T05:37:39.755+0000] {processor.py:186} INFO - Started process (PID=1500) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:37:39.756+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:37:39.758+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:37:39.757+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:37:39.764+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:37:39.763+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:37:39.765+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:37:39.777+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.026 seconds
[2025-03-25T05:38:10.131+0000] {processor.py:186} INFO - Started process (PID=1566) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:38:10.133+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:38:10.136+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:38:10.136+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:38:10.144+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:38:10.143+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:38:10.145+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:38:10.158+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.032 seconds
[2025-03-25T05:38:40.190+0000] {processor.py:186} INFO - Started process (PID=1631) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:38:40.191+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:38:40.193+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:38:40.193+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:38:40.200+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:38:40.199+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:38:40.201+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:38:40.213+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.029 seconds
[2025-03-25T05:39:10.362+0000] {processor.py:186} INFO - Started process (PID=1699) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:39:10.363+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:39:10.365+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:39:10.365+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:39:10.373+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:39:10.372+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:39:10.374+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:39:10.385+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.027 seconds
[2025-03-25T05:39:40.578+0000] {processor.py:186} INFO - Started process (PID=1766) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:39:40.579+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:39:40.582+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:39:40.582+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:39:40.588+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:39:40.588+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:39:40.589+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:39:40.599+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.025 seconds
[2025-03-25T05:40:10.816+0000] {processor.py:186} INFO - Started process (PID=1833) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:40:10.817+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:40:10.818+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:40:10.818+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:40:10.824+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:40:10.823+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:40:10.825+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:40:10.839+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.026 seconds
[2025-03-25T05:40:41.127+0000] {processor.py:186} INFO - Started process (PID=1900) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:40:41.128+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:40:41.131+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:40:41.131+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:40:41.138+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:40:41.137+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:40:41.141+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:40:41.154+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.031 seconds
[2025-03-25T05:41:11.212+0000] {processor.py:186} INFO - Started process (PID=1967) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:41:11.213+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:41:11.214+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:41:11.214+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:41:11.222+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:41:11.221+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:41:11.222+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:41:11.234+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.025 seconds
[2025-03-25T05:41:41.288+0000] {processor.py:186} INFO - Started process (PID=2033) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:41:41.290+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:41:41.292+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:41:41.292+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:41:41.301+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:41:41.300+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:41:41.302+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:41:41.317+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.035 seconds
[2025-03-25T05:42:11.859+0000] {processor.py:186} INFO - Started process (PID=2100) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:42:11.860+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:42:11.863+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:42:11.862+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:42:11.874+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:42:11.873+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:42:11.876+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:42:11.887+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.032 seconds
[2025-03-25T05:42:42.268+0000] {processor.py:186} INFO - Started process (PID=2167) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:42:42.269+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:42:42.273+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:42:42.272+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:42:42.282+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:42:42.281+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:42:42.285+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:42:42.296+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.032 seconds
[2025-03-25T05:43:12.684+0000] {processor.py:186} INFO - Started process (PID=2234) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:43:12.685+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:43:12.688+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:43:12.688+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:43:12.697+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:43:12.696+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:43:12.697+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:43:12.713+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.034 seconds
[2025-03-25T05:43:42.752+0000] {processor.py:186} INFO - Started process (PID=2300) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:43:42.753+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:43:42.755+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:43:42.754+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:43:42.761+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:43:42.760+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:43:42.762+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:43:42.776+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.030 seconds
[2025-03-25T05:44:13.203+0000] {processor.py:186} INFO - Started process (PID=2368) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:44:13.203+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:44:13.205+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:44:13.204+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:44:13.212+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:44:13.211+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:44:13.213+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:44:13.231+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.032 seconds
[2025-03-25T05:44:43.559+0000] {processor.py:186} INFO - Started process (PID=2434) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:44:43.560+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:44:43.561+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:44:43.561+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:44:43.566+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:44:43.565+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:44:43.567+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:44:43.575+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.018 seconds
[2025-03-25T05:45:14.070+0000] {processor.py:186} INFO - Started process (PID=2501) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:45:14.070+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:45:14.071+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:45:14.071+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:45:14.074+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:45:14.074+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:45:14.075+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:45:14.082+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.013 seconds
[2025-03-25T05:45:45.025+0000] {processor.py:186} INFO - Started process (PID=2568) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:45:45.025+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:45:45.026+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:45:45.026+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:45:45.028+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:45:45.028+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:45:45.029+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:45:45.036+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.014 seconds
[2025-03-25T05:46:15.283+0000] {processor.py:186} INFO - Started process (PID=2633) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:46:15.284+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:46:15.285+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:46:15.285+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:46:15.290+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:46:15.289+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:46:15.290+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:46:15.300+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.020 seconds
[2025-03-25T05:46:43.781+0000] {processor.py:186} INFO - Started process (PID=2699) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:46:43.781+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:46:43.783+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:46:43.783+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:46:43.791+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:46:43.790+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:46:43.791+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:46:43.804+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.029 seconds
[2025-03-25T05:47:14.599+0000] {processor.py:186} INFO - Started process (PID=2766) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:47:14.600+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:47:14.603+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:47:14.603+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:47:14.610+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:47:14.608+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:47:14.610+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:47:14.622+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.029 seconds
[2025-03-25T05:47:44.675+0000] {processor.py:186} INFO - Started process (PID=2833) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:47:44.676+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:47:44.679+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:47:44.678+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:47:44.686+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:47:44.685+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:47:44.686+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:47:44.700+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.031 seconds
[2025-03-25T05:48:15.303+0000] {processor.py:186} INFO - Started process (PID=2900) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:48:15.304+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:48:15.306+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:48:15.306+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:48:15.313+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:48:15.311+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:48:15.313+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:48:15.327+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.030 seconds
[2025-03-25T05:48:45.522+0000] {processor.py:186} INFO - Started process (PID=2967) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:48:45.523+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:48:45.524+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:48:45.524+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:48:45.530+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:48:45.529+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:48:45.530+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:48:45.541+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.024 seconds
[2025-03-25T05:49:16.314+0000] {processor.py:186} INFO - Started process (PID=3034) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:49:16.315+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:49:16.317+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:49:16.316+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:49:16.323+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:49:16.322+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:49:16.323+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:49:16.335+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.027 seconds
[2025-03-25T05:49:47.099+0000] {processor.py:186} INFO - Started process (PID=3101) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:49:47.100+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:49:47.103+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:49:47.102+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:49:47.109+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:49:47.108+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:49:47.110+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:49:47.122+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.028 seconds
[2025-03-25T05:50:17.908+0000] {processor.py:186} INFO - Started process (PID=3168) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:50:17.909+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:50:17.911+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:50:17.911+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:50:17.918+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:50:17.917+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:50:17.919+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:50:17.932+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.030 seconds
[2025-03-25T05:50:48.635+0000] {processor.py:186} INFO - Started process (PID=3234) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:50:48.637+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:50:48.640+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:50:48.639+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:50:48.647+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:50:48.646+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:50:48.648+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:50:48.661+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.033 seconds
[2025-03-25T05:51:19.568+0000] {processor.py:186} INFO - Started process (PID=3301) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:51:19.569+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:51:19.571+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:51:19.570+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:51:19.577+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:51:19.576+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:51:19.578+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:51:19.591+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.028 seconds
[2025-03-25T05:51:50.538+0000] {processor.py:186} INFO - Started process (PID=3368) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:51:50.539+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:51:50.541+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:51:50.540+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:51:50.547+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:51:50.546+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:51:50.547+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:51:50.560+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.028 seconds
[2025-03-25T05:52:21.067+0000] {processor.py:186} INFO - Started process (PID=3435) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:52:21.067+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:52:21.068+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:52:21.068+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:52:21.074+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:52:21.073+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:52:21.074+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:52:21.083+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.020 seconds
[2025-03-25T05:52:51.883+0000] {processor.py:186} INFO - Started process (PID=3502) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:52:51.885+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:52:51.886+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:52:51.886+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:52:51.891+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:52:51.891+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:52:51.892+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:52:51.900+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.020 seconds
[2025-03-25T05:53:22.673+0000] {processor.py:186} INFO - Started process (PID=3569) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:53:22.673+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:53:22.676+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:53:22.676+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:53:22.682+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:53:22.681+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:53:22.683+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:53:22.696+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.029 seconds
[2025-03-25T05:53:53.550+0000] {processor.py:186} INFO - Started process (PID=3636) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:53:53.551+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:53:53.554+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:53:53.553+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:53:53.560+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:53:53.559+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:53:53.560+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:53:53.572+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.028 seconds
[2025-03-25T05:54:23.965+0000] {processor.py:186} INFO - Started process (PID=3703) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:54:23.966+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:54:23.969+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:54:23.968+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:54:23.975+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:54:23.974+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:54:23.975+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:54:23.988+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.028 seconds
[2025-03-25T05:54:54.825+0000] {processor.py:186} INFO - Started process (PID=3770) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:54:54.826+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:54:54.828+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:54:54.828+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:54:54.834+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:54:54.833+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:54:54.835+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:54:54.847+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.028 seconds
[2025-03-25T05:55:25.781+0000] {processor.py:186} INFO - Started process (PID=3837) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:55:25.782+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:55:25.784+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:55:25.784+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:55:25.790+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:55:25.789+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:55:25.791+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:55:25.803+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.029 seconds
[2025-03-25T05:55:56.620+0000] {processor.py:186} INFO - Started process (PID=3904) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:55:56.620+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:55:56.621+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:55:56.621+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:55:56.626+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:55:56.625+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:55:56.626+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:55:56.634+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.019 seconds
[2025-03-25T05:56:27.088+0000] {processor.py:186} INFO - Started process (PID=3971) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:56:27.089+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:56:27.091+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:56:27.091+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:56:27.096+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:56:27.095+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:56:27.097+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:56:27.108+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.026 seconds
[2025-03-25T05:56:57.896+0000] {processor.py:186} INFO - Started process (PID=4038) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:56:57.897+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:56:57.899+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:56:57.899+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:56:57.905+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:56:57.904+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:56:57.905+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:56:57.917+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.026 seconds
[2025-03-25T05:57:28.826+0000] {processor.py:186} INFO - Started process (PID=4105) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:57:28.827+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:57:28.829+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:57:28.829+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:57:28.835+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:57:28.834+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:57:28.836+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:57:28.845+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.023 seconds
[2025-03-25T05:57:59.660+0000] {processor.py:186} INFO - Started process (PID=4172) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:57:59.661+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:57:59.663+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:57:59.663+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:57:59.670+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:57:59.669+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:57:59.670+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:57:59.683+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.030 seconds
[2025-03-25T05:58:30.642+0000] {processor.py:186} INFO - Started process (PID=4239) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:58:30.642+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:58:30.645+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:58:30.645+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:58:30.651+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:58:30.650+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:58:30.651+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:58:30.664+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.027 seconds
[2025-03-25T05:59:01.204+0000] {processor.py:186} INFO - Started process (PID=4305) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:59:01.206+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:59:01.208+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:59:01.207+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:59:01.213+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:59:01.212+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:59:01.213+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:59:01.223+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.023 seconds
[2025-03-25T05:59:31.235+0000] {processor.py:186} INFO - Started process (PID=4371) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T05:59:31.235+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T05:59:31.236+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:59:31.236+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T05:59:31.239+0000] {logging_mixin.py:190} INFO - [2025-03-25T05:59:31.239+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T05:59:31.240+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T05:59:31.246+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.014 seconds
[2025-03-25T06:00:01.294+0000] {processor.py:186} INFO - Started process (PID=4438) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T06:00:01.294+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T06:00:01.296+0000] {logging_mixin.py:190} INFO - [2025-03-25T06:00:01.296+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T06:00:01.300+0000] {logging_mixin.py:190} INFO - [2025-03-25T06:00:01.299+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T06:00:01.300+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T06:00:01.308+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.017 seconds
[2025-03-25T06:00:31.727+0000] {processor.py:186} INFO - Started process (PID=4504) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T06:00:31.728+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T06:00:31.730+0000] {logging_mixin.py:190} INFO - [2025-03-25T06:00:31.730+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T06:00:31.736+0000] {logging_mixin.py:190} INFO - [2025-03-25T06:00:31.735+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T06:00:31.737+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T06:00:31.748+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.026 seconds
[2025-03-25T06:01:02.029+0000] {processor.py:186} INFO - Started process (PID=4571) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T06:01:02.030+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T06:01:02.033+0000] {logging_mixin.py:190} INFO - [2025-03-25T06:01:02.033+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T06:01:02.039+0000] {logging_mixin.py:190} INFO - [2025-03-25T06:01:02.038+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T06:01:02.040+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T06:01:02.053+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.028 seconds
[2025-03-25T06:01:32.087+0000] {processor.py:186} INFO - Started process (PID=4638) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T06:01:32.088+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T06:01:32.091+0000] {logging_mixin.py:190} INFO - [2025-03-25T06:01:32.091+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T06:01:32.098+0000] {logging_mixin.py:190} INFO - [2025-03-25T06:01:32.096+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T06:01:32.098+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T06:01:32.110+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.029 seconds
[2025-03-25T06:02:02.294+0000] {processor.py:186} INFO - Started process (PID=4705) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T06:02:02.295+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T06:02:02.298+0000] {logging_mixin.py:190} INFO - [2025-03-25T06:02:02.298+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T06:02:02.304+0000] {logging_mixin.py:190} INFO - [2025-03-25T06:02:02.303+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T06:02:02.304+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T06:02:02.313+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.025 seconds
[2025-03-25T06:02:32.402+0000] {processor.py:186} INFO - Started process (PID=4772) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T06:02:32.403+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T06:02:32.406+0000] {logging_mixin.py:190} INFO - [2025-03-25T06:02:32.405+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T06:02:32.413+0000] {logging_mixin.py:190} INFO - [2025-03-25T06:02:32.412+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T06:02:32.413+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T06:02:32.423+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.026 seconds
[2025-03-25T06:03:02.842+0000] {processor.py:186} INFO - Started process (PID=4839) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T06:03:02.843+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T06:03:02.845+0000] {logging_mixin.py:190} INFO - [2025-03-25T06:03:02.845+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T06:03:02.852+0000] {logging_mixin.py:190} INFO - [2025-03-25T06:03:02.851+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T06:03:02.852+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T06:03:02.864+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.027 seconds
[2025-03-25T06:03:33.183+0000] {processor.py:186} INFO - Started process (PID=4906) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T06:03:33.184+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T06:03:33.187+0000] {logging_mixin.py:190} INFO - [2025-03-25T06:03:33.187+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T06:03:33.194+0000] {logging_mixin.py:190} INFO - [2025-03-25T06:03:33.193+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T06:03:33.195+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T06:03:33.206+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.030 seconds
[2025-03-25T06:04:03.442+0000] {processor.py:186} INFO - Started process (PID=4972) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T06:04:03.442+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T06:04:03.445+0000] {logging_mixin.py:190} INFO - [2025-03-25T06:04:03.445+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T06:04:03.452+0000] {logging_mixin.py:190} INFO - [2025-03-25T06:04:03.451+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T06:04:03.453+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T06:04:03.464+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.028 seconds
[2025-03-25T06:04:33.506+0000] {processor.py:186} INFO - Started process (PID=5039) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T06:04:33.507+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T06:04:33.509+0000] {logging_mixin.py:190} INFO - [2025-03-25T06:04:33.509+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T06:04:33.516+0000] {logging_mixin.py:190} INFO - [2025-03-25T06:04:33.515+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T06:04:33.517+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T06:04:33.528+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.028 seconds
[2025-03-25T06:05:04.024+0000] {processor.py:186} INFO - Started process (PID=5106) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T06:05:04.024+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T06:05:04.027+0000] {logging_mixin.py:190} INFO - [2025-03-25T06:05:04.026+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T06:05:04.033+0000] {logging_mixin.py:190} INFO - [2025-03-25T06:05:04.032+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T06:05:04.033+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T06:05:04.046+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.027 seconds
[2025-03-25T06:05:34.440+0000] {processor.py:186} INFO - Started process (PID=5173) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T06:05:34.441+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T06:05:34.444+0000] {logging_mixin.py:190} INFO - [2025-03-25T06:05:34.443+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T06:05:34.450+0000] {logging_mixin.py:190} INFO - [2025-03-25T06:05:34.449+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T06:05:34.450+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T06:05:34.463+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.028 seconds
[2025-03-25T06:06:04.860+0000] {processor.py:186} INFO - Started process (PID=5240) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T06:06:04.861+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T06:06:04.863+0000] {logging_mixin.py:190} INFO - [2025-03-25T06:06:04.863+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T06:06:04.869+0000] {logging_mixin.py:190} INFO - [2025-03-25T06:06:04.868+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T06:06:04.869+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T06:06:04.881+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.025 seconds
[2025-03-25T06:06:35.129+0000] {processor.py:186} INFO - Started process (PID=5307) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T06:06:35.130+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T06:06:35.132+0000] {logging_mixin.py:190} INFO - [2025-03-25T06:06:35.132+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T06:06:35.138+0000] {logging_mixin.py:190} INFO - [2025-03-25T06:06:35.137+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
  File "/opt/airflow/plugins/scripts/extract/news_extract.py", line 5, in <module>
    from config.settings import CLIENT_ID, CLIENT_SECRET
ImportError: cannot import name 'CLIENT_ID' from 'config.settings' (/opt/airflow/plugins/config/settings.py)
[2025-03-25T06:06:35.139+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T06:06:35.149+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.024 seconds
[2025-03-25T06:07:05.783+0000] {processor.py:186} INFO - Started process (PID=5374) to work on /opt/airflow/dags/news_dag.py
[2025-03-25T06:07:05.784+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/news_dag.py for tasks to queue
[2025-03-25T06:07:05.786+0000] {logging_mixin.py:190} INFO - [2025-03-25T06:07:05.786+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/news_dag.py
[2025-03-25T06:07:05.792+0000] {logging_mixin.py:190} INFO - [2025-03-25T06:07:05.791+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/news_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/news_dag.py", line 4, in <module>
    from scripts.extract.news_extract import NaverBlogExtractor
ModuleNotFoundError: No module named 'scripts.extract.news_extract'
[2025-03-25T06:07:05.793+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/news_dag.py
[2025-03-25T06:07:05.804+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/news_dag.py took 0.027 seconds
