[2025-03-15T22:06:09.997+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-15T22:06:10.070+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: instant_stock_dag.load manual__2025-03-15T22:04:38.348385+00:00 [queued]>
[2025-03-15T22:06:10.105+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: instant_stock_dag.load manual__2025-03-15T22:04:38.348385+00:00 [queued]>
[2025-03-15T22:06:10.107+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-15T22:06:10.135+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load> on 2025-03-15 22:04:38.348385+00:00
[2025-03-15T22:06:10.160+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'instant_stock_dag', 'load', 'manual__2025-03-15T22:04:38.348385+00:00', '--job-id', '191', '--raw', '--subdir', 'DAGS_FOLDER/blog_dag.py', '--cfg-path', '/tmp/tmplgj7g6x6']
[2025-03-15T22:06:10.161+0000] {standard_task_runner.py:105} INFO - Job 191: Subtask load
[2025-03-15T22:06:10.164+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=390) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-15T22:06:10.168+0000] {standard_task_runner.py:72} INFO - Started process 391 to run task
[2025-03-15T22:06:10.278+0000] {task_command.py:467} INFO - Running <TaskInstance: instant_stock_dag.load manual__2025-03-15T22:04:38.348385+00:00 [running]> on host fcb5806ac743
[2025-03-15T22:06:10.461+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='instant_stock_dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2025-03-15T22:04:38.348385+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-15T22:04:38.348385+00:00'
[2025-03-15T22:06:10.463+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-15T22:06:10.464+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-15T22:06:10.465+0000] {logging_mixin.py:190} INFO - Current task name:load state:running start_date:2025-03-15 22:06:10.071745+00:00
[2025-03-15T22:06:10.466+0000] {logging_mixin.py:190} INFO - Dag name:instant_stock_dag and current dag run status:running
[2025-03-15T22:06:10.467+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-15T22:06:10.481+0000] {warnings.py:112} WARNING - /opt/***/dags/blog_dag.py:66: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_json(df_json, orient="records")  # ✅ split → records로 변경

[2025-03-15T22:06:10.512+0000] {logging_mixin.py:190} INFO - ✅ Loaded 248 rows from XCom
[2025-03-15T22:06:10.520+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/blog_dag.py", line 123, in load
    load_stock_data(extracted_data_json)
  File "/opt/airflow/dags/blog_dag.py", line 77, in load_stock_data
    cur.execute("""
psycopg2.errors.InvalidColumnReference: there is no unique or exclusion constraint matching the ON CONFLICT specification

[2025-03-15T22:06:10.533+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-15T22:06:10.534+0000] {logging_mixin.py:190} INFO - Task start:2025-03-15 22:06:10.071745+00:00 end:2025-03-15 22:06:10.532935+00:00 duration:0.46119
[2025-03-15T22:06:10.535+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): load> dag:<DAG: instant_stock_dag> dagrun:<DagRun instant_stock_dag @ 2025-03-15 22:04:38.348385+00:00: manual__2025-03-15T22:04:38.348385+00:00, state:running, queued_at: 2025-03-15 22:04:38.363559+00:00. externally triggered: True>
[2025-03-15T22:06:10.535+0000] {logging_mixin.py:190} INFO - Failure caused by there is no unique or exclusion constraint matching the ON CONFLICT specification
[2025-03-15T22:06:10.535+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=instant_stock_dag, task_id=load, run_id=manual__2025-03-15T22:04:38.348385+00:00, execution_date=20250315T220438, start_date=20250315T220610, end_date=20250315T220610
[2025-03-15T22:06:10.556+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-15T22:06:10.558+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 191 for task load (there is no unique or exclusion constraint matching the ON CONFLICT specification
; 391)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/blog_dag.py", line 123, in load
    load_stock_data(extracted_data_json)
  File "/opt/airflow/dags/blog_dag.py", line 77, in load_stock_data
    cur.execute("""
psycopg2.errors.InvalidColumnReference: there is no unique or exclusion constraint matching the ON CONFLICT specification

[2025-03-15T22:06:10.601+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-15T22:06:10.623+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-15T22:06:10.624+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
