[2025-03-16T00:46:30.936+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-16T00:46:30.956+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_trend_dag.extract manual__2025-03-16T00:46:28.535856+00:00 [queued]>
[2025-03-16T00:46:30.984+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_trend_dag.extract manual__2025-03-16T00:46:28.535856+00:00 [queued]>
[2025-03-16T00:46:30.986+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-16T00:46:31.024+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract> on 2025-03-16 00:46:28.535856+00:00
[2025-03-16T00:46:31.030+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=151) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-16T00:46:31.035+0000] {standard_task_runner.py:72} INFO - Started process 152 to run task
[2025-03-16T00:46:31.054+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'google_trend_dag', 'extract', 'manual__2025-03-16T00:46:28.535856+00:00', '--job-id', '231', '--raw', '--subdir', 'DAGS_FOLDER/trend_dag.py', '--cfg-path', '/tmp/tmp6s22abk0']
[2025-03-16T00:46:31.058+0000] {standard_task_runner.py:105} INFO - Job 231: Subtask extract
[2025-03-16T00:46:31.118+0000] {task_command.py:467} INFO - Running <TaskInstance: google_trend_dag.extract manual__2025-03-16T00:46:28.535856+00:00 [running]> on host c8b801ec24ca
[2025-03-16T00:46:31.218+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_trend_dag' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-03-16T00:46:28.535856+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-16T00:46:28.535856+00:00'
[2025-03-16T00:46:31.221+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-16T00:46:31.222+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-16T00:46:31.224+0000] {logging_mixin.py:190} INFO - Current task name:extract state:running start_date:2025-03-16 00:46:30.959374+00:00
[2025-03-16T00:46:31.224+0000] {logging_mixin.py:190} INFO - Dag name:google_trend_dag and current dag run status:running
[2025-03-16T00:46:31.225+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-16T00:46:37.839+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/trend_dag.py", line 44, in extract_pytrends
    pytrends.build_payload(kw_list=keywords, timeframe=PERIOD, geo='KR')
  File "/home/airflow/.local/lib/python3.12/site-packages/pytrends/request.py", line 189, in build_payload
    self._tokens()
  File "/home/airflow/.local/lib/python3.12/site-packages/pytrends/request.py", line 195, in _tokens
    widget_dicts = self._get_data(
                   ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pytrends/request.py", line 160, in _get_data
    raise exceptions.ResponseError.from_response(response)
pytrends.exceptions.ResponseError: The request failed: Google returned a response with code 400
[2025-03-16T00:46:37.883+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-16T00:46:37.885+0000] {logging_mixin.py:190} INFO - Task start:2025-03-16 00:46:30.959374+00:00 end:2025-03-16 00:46:37.881603+00:00 duration:6.922229
[2025-03-16T00:46:37.886+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract> dag:<DAG: google_trend_dag> dagrun:<DagRun google_trend_dag @ 2025-03-16 00:46:28.535856+00:00: manual__2025-03-16T00:46:28.535856+00:00, state:running, queued_at: 2025-03-16 00:46:28.547918+00:00. externally triggered: True>
[2025-03-16T00:46:37.889+0000] {logging_mixin.py:190} INFO - Failure caused by The request failed: Google returned a response with code 400
[2025-03-16T00:46:37.892+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=google_trend_dag, task_id=extract, run_id=manual__2025-03-16T00:46:28.535856+00:00, execution_date=20250316T004628, start_date=20250316T004630, end_date=20250316T004637
[2025-03-16T00:46:37.938+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-16T00:46:37.939+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 231 for task extract (The request failed: Google returned a response with code 400; 152)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/trend_dag.py", line 44, in extract_pytrends
    pytrends.build_payload(kw_list=keywords, timeframe=PERIOD, geo='KR')
  File "/home/airflow/.local/lib/python3.12/site-packages/pytrends/request.py", line 189, in build_payload
    self._tokens()
  File "/home/airflow/.local/lib/python3.12/site-packages/pytrends/request.py", line 195, in _tokens
    widget_dicts = self._get_data(
                   ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pytrends/request.py", line 160, in _get_data
    raise exceptions.ResponseError.from_response(response)
pytrends.exceptions.ResponseError: The request failed: Google returned a response with code 400
[2025-03-16T00:46:37.952+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-16T00:46:37.996+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-16T00:46:38.006+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
