[2025-03-15T20:03:35.686+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-15T20:03:35.697+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: instant_stock_dag.load scheduled__2025-03-14T10:00:00+00:00 [queued]>
[2025-03-15T20:03:35.703+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: instant_stock_dag.load scheduled__2025-03-14T10:00:00+00:00 [queued]>
[2025-03-15T20:03:35.704+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-15T20:03:35.713+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load> on 2025-03-14 10:00:00+00:00
[2025-03-15T20:03:35.719+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=663) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-15T20:03:35.720+0000] {standard_task_runner.py:72} INFO - Started process 666 to run task
[2025-03-15T20:03:35.721+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'instant_stock_dag', 'load', 'scheduled__2025-03-14T10:00:00+00:00', '--job-id', '153', '--raw', '--subdir', 'DAGS_FOLDER/blog_dag.py', '--cfg-path', '/tmp/tmpm3nyt6j8']
[2025-03-15T20:03:35.722+0000] {standard_task_runner.py:105} INFO - Job 153: Subtask load
[2025-03-15T20:03:35.771+0000] {task_command.py:467} INFO - Running <TaskInstance: instant_stock_dag.load scheduled__2025-03-14T10:00:00+00:00 [running]> on host 3e318d6013a3
[2025-03-15T20:03:35.835+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='instant_stock_dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2025-03-14T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-14T10:00:00+00:00'
[2025-03-15T20:03:35.836+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-15T20:03:35.837+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-15T20:03:35.837+0000] {logging_mixin.py:190} INFO - Current task name:load state:running start_date:2025-03-15 20:03:35.697697+00:00
[2025-03-15T20:03:35.837+0000] {logging_mixin.py:190} INFO - Dag name:instant_stock_dag and current dag run status:running
[2025-03-15T20:03:35.837+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-15T20:03:35.842+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-15T20:03:35.849+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-15T20:03:35.850+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=instant_stock_dag, task_id=load, run_id=scheduled__2025-03-14T10:00:00+00:00, execution_date=20250314T100000, start_date=20250315T200335, end_date=20250315T200335
[2025-03-15T20:03:35.862+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-15T20:03:35.863+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-15T20:03:35.864+0000] {logging_mixin.py:190} INFO - Dag name:instant_stock_dag queued_at:2025-03-15 20:02:04.103210+00:00
[2025-03-15T20:03:35.864+0000] {logging_mixin.py:190} INFO - Task hostname:3e318d6013a3 operator:PythonOperator
[2025-03-15T20:03:35.900+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-15T20:03:35.910+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-15T20:03:35.911+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-15T21:30:07.540+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-15T21:30:07.560+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: instant_stock_dag.load scheduled__2025-03-14T10:00:00+00:00 [queued]>
[2025-03-15T21:30:07.579+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: instant_stock_dag.load scheduled__2025-03-14T10:00:00+00:00 [queued]>
[2025-03-15T21:30:07.580+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-15T21:30:07.595+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load> on 2025-03-14 10:00:00+00:00
[2025-03-15T21:30:07.605+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1009) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-15T21:30:07.607+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'instant_stock_dag', 'load', 'scheduled__2025-03-14T10:00:00+00:00', '--job-id', '178', '--raw', '--subdir', 'DAGS_FOLDER/blog_dag.py', '--cfg-path', '/tmp/tmpx4f0h7jm']
[2025-03-15T21:30:07.608+0000] {standard_task_runner.py:105} INFO - Job 178: Subtask load
[2025-03-15T21:30:07.608+0000] {standard_task_runner.py:72} INFO - Started process 1010 to run task
[2025-03-15T21:30:07.643+0000] {task_command.py:467} INFO - Running <TaskInstance: instant_stock_dag.load scheduled__2025-03-14T10:00:00+00:00 [running]> on host a212aa202656
[2025-03-15T21:30:07.686+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='instant_stock_dag' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2025-03-14T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-14T10:00:00+00:00'
[2025-03-15T21:30:07.687+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-15T21:30:07.687+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-15T21:30:07.688+0000] {logging_mixin.py:190} INFO - Current task name:load state:running start_date:2025-03-15 21:30:07.562129+00:00
[2025-03-15T21:30:07.688+0000] {logging_mixin.py:190} INFO - Dag name:instant_stock_dag and current dag run status:running
[2025-03-15T21:30:07.689+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-15T21:30:07.717+0000] {warnings.py:112} WARNING - /opt/***/dags/blog_dag.py:56: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_json(df_json, orient="split")

[2025-03-15T21:30:07.867+0000] {logging_mixin.py:190} INFO - âœ… Loaded 248 rows from XCom
[2025-03-15T21:30:07.876+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3791, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 152, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 181, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Date'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/blog_dag.py", line 110, in load
    load_stock_data(extracted_data_json)
  File "/opt/airflow/dags/blog_dag.py", line 72, in load_stock_data
    row["Date"], row["stock_code"], row["Close"],
    ~~~^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/series.py", line 1040, in __getitem__
    return self._get_value(key)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/series.py", line 1156, in _get_value
    loc = self.index.get_loc(label)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3798, in get_loc
    raise KeyError(key) from err
KeyError: 'Date'
[2025-03-15T21:30:07.885+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-15T21:30:07.885+0000] {logging_mixin.py:190} INFO - Task start:2025-03-15 21:30:07.562129+00:00 end:2025-03-15 21:30:07.885184+00:00 duration:0.323055
[2025-03-15T21:30:07.886+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): load> dag:<DAG: instant_stock_dag> dagrun:<DagRun instant_stock_dag @ 2025-03-14 10:00:00+00:00: scheduled__2025-03-14T10:00:00+00:00, state:running, queued_at: 2025-03-15 21:16:46.254164+00:00. externally triggered: False>
[2025-03-15T21:30:07.886+0000] {logging_mixin.py:190} INFO - Failure caused by 'Date'
[2025-03-15T21:30:07.889+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=instant_stock_dag, task_id=load, run_id=scheduled__2025-03-14T10:00:00+00:00, execution_date=20250314T100000, start_date=20250315T213007, end_date=20250315T213007
[2025-03-15T21:30:07.911+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-15T21:30:07.912+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 178 for task load ('Date'; 1010)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3791, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 152, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 181, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Date'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/blog_dag.py", line 110, in load
    load_stock_data(extracted_data_json)
  File "/opt/airflow/dags/blog_dag.py", line 72, in load_stock_data
    row["Date"], row["stock_code"], row["Close"],
    ~~~^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/series.py", line 1040, in __getitem__
    return self._get_value(key)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/series.py", line 1156, in _get_value
    loc = self.index.get_loc(label)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3798, in get_loc
    raise KeyError(key) from err
KeyError: 'Date'
[2025-03-15T21:30:07.919+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-15T21:30:07.978+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-15T21:30:07.983+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
